In [1]:
import numpy as np

In [2]:
list = [1, 2, 3]

In [4]:
arr = np.array(list)
arr

array([1, 2, 3])

In [5]:
nested_list = [[1, 2, 3], [6, 4, 6], [1, 8, 7]]
nested_list

[[1, 2, 3], [6, 4, 6], [1, 8, 7]]

In [6]:
np.array(nested_list)

array([[1, 2, 3],
       [6, 4, 6],
       [1, 8, 7]])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(5, 16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.linspace(5,15,40)

array([ 5.        ,  5.25641026,  5.51282051,  5.76923077,  6.02564103,
        6.28205128,  6.53846154,  6.79487179,  7.05128205,  7.30769231,
        7.56410256,  7.82051282,  8.07692308,  8.33333333,  8.58974359,
        8.84615385,  9.1025641 ,  9.35897436,  9.61538462,  9.87179487,
       10.12820513, 10.38461538, 10.64102564, 10.8974359 , 11.15384615,
       11.41025641, 11.66666667, 11.92307692, 12.17948718, 12.43589744,
       12.69230769, 12.94871795, 13.20512821, 13.46153846, 13.71794872,
       13.97435897, 14.23076923, 14.48717949, 14.74358974, 15.        ])

In [18]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(3)

array([0.13048811, 0.79005073, 0.17631615])

In [20]:
np.random.rand(3,4)

array([[0.55888006, 0.31229735, 0.89887208, 0.63556489],
       [0.33355095, 0.86221343, 0.56758537, 0.91624714],
       [0.0911741 , 0.2379354 , 0.48329267, 0.77948249]])

In [21]:
np.random.randn(5,6) #sd , mean = 0, Var = 1 

array([[ 0.27373061, -1.68515634, -0.50795507, -0.8542349 , -0.37064133,
        -1.11000442],
       [-0.04345445,  0.83903551, -0.67898038, -0.22642187,  0.13748176,
         1.27364918],
       [ 0.20599305,  2.18211908,  0.35558997, -1.35446636,  0.48040032,
        -0.92132611],
       [-0.54299453,  0.94569608, -2.11710596,  1.19474495, -1.47139962,
         0.34446869],
       [-0.03107172,  0.98413045, -1.4087592 ,  0.54541458, -0.11130374,
        -0.06931449]])

In [23]:
np.random.randint(100, 555)

554

In [26]:
np.random.randint(100, 555, 10)

array([111, 132, 254, 134, 227, 463, 145, 351, 180, 222])

In [27]:
np.random.randint(12, 14, (2,10))

array([[13, 12, 13, 12, 13, 13, 13, 13, 12, 13],
       [13, 13, 13, 12, 13, 13, 12, 12, 13, 12]])

In [28]:
np.random.seed(42)
np.random.randn(5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

In [30]:
arr1= np.arange(1,26)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [32]:
ranarr = np.random.randint(10, 50, 10)
ranarr

array([39, 47, 11, 30, 42, 21, 31, 34, 36, 37])

In [33]:
arr1.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
ranarr.max()

47

In [38]:
ranarr.argmax()

1

In [39]:
ranarr.min()

11

## Broadcasting

In [42]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr2[5]

5

In [44]:
arr2[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr2[0:5]=100
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [47]:
slice_of = arr2[2:4]
slice_of

array([100, 100])

In [48]:
slice_of[:]=77
arr2

array([100, 100,  77,  77, 100,   5,   6,   7,   8,   9])

In [52]:
arr_2d = np.array([[1, 9, 3], [6, 4, 8], [1, 4, 7]])
arr_2d

array([[1, 9, 3],
       [6, 4, 8],
       [1, 4, 7]])

In [55]:
arr_2d.shape

(3, 3)

In [56]:
arr_2d[:2]

array([[1, 9, 3],
       [6, 4, 8]])

In [57]:
arr_2d[:2,:2]

array([[1, 9],
       [6, 4]])

In [58]:
arr_2d[1, 1]

4

## Conditional selection

In [61]:
arr4 = np.random.randint(5,50,10)
arr4

array([12, 39, 18, 21, 40, 44,  8,  6, 10, 46])

In [62]:
arr4[arr4>10]

array([12, 39, 18, 21, 40, 44, 46])

## numpy Operation

In [65]:
arr5=np.arange(21, 31)
arr5

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [66]:
arr5 + arr5

array([42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [67]:
arr5 * arr5

array([441, 484, 529, 576, 625, 676, 729, 784, 841, 900])

## Excersize

In [75]:
arr = np.arange(0,1,.01)
arr.reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [80]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [87]:
mast = np.arange(1,26).reshape(5,5)
mast

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [88]:
sub = mast[2:,1:]
sub

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [89]:
mast[3,4]

20

In [92]:
mini = mast[:3,:2]
mini[:, 1:]


array([[ 2],
       [ 7],
       [12]])

In [94]:
mast[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [95]:
mast.sum()

325

In [96]:
mast.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [97]:
mast.sum(axis=0)

array([55, 60, 65, 70, 75])

In [99]:
mast.std()

7.211102550927978